Parameters:
  Environment:
    Description: "The environment this application should run in."
    Type: String
    Default: development  
  SiteWhitelistIps:
    Description: "(optional) A comma-separated list of IP addresses to whitelist the entire website."
    Type: String
    Default: ""
  BucketName:
    Description: "The S3 bucket to create"
    Type: String

Mappings:
  EnvironmentMap:
    demo:
      fr: fr 

Conditions:
  HasSiteIpWhitelist: !Not [ !Equals [ !Ref SiteWhitelistIps, "" ] ]
  DoesNotHaveSiteIpWhitelist: !Equals [ !Ref SiteWhitelistIps, "" ]

Outputs:
  StorageBucketName:
    Description: "The S3 bucket for media uploads"
    Value: !Ref Storage     
    Export:
      Name: !Join [ "", [ !Ref "AWS::StackName", "-StorageBucketName" ] ]  
  SNSTopic:
    Description: "The SNS queue attached to the media uploads bucket; used by yas3fs to notify of changes in the bucket"  
    Value: !Ref StorageTopic
    Export:
      Name: !Join [ "", [ !Ref "AWS::StackName", "-SNSTopic" ] ]
    

Resources:    
  ##
  # Uploads storage
  ##
  Storage:
    Type: AWS::S3::Bucket
    DeletionPolicy : "Retain"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "Delete old backup versions after 30 days"
            NoncurrentVersionExpirationInDays: 30
            Status: Enabled
  StorageBucketPolicyWhitelisted:
    Type: AWS::S3::BucketPolicy
    Condition: HasSiteIpWhitelist
    Properties:
      Bucket: !Ref Storage
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref Storage, '/uploads/*' ] ]
            Principal: "*"
            Condition:
              IpAddress:
                aws:SourceIp: !Split [ "," , !Ref SiteWhitelistIps ]
  StorageBucketPolicyPublic:
    Type: AWS::S3::BucketPolicy
    Condition: DoesNotHaveSiteIpWhitelist
    Properties:
      Bucket: !Ref Storage
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref Storage, '/uploads/*' ] ]
            Principal: "*"
  StorageTopic:
    Type: AWS::SNS::Topic
  