Parameters:
  Environment:
    Description: "The environment this application should run in."
    Type: String
    Default: development  
  SiteWhitelistIps:
    Description: "(optional) A comma-separated list of IP addresses to whitelist the entire website."
    Type: String
    Default: ""
  BucketName:
    Description: "The S3 bucket to create"
    Type: String
Mappings:
  EnvironmentMap:
    demo:
      StorageUserGroups:
        - DemoIntranetSites

Conditions:
  HasSiteIpWhitelist: !Not [ !Equals [ !Ref SiteWhitelistIps, "" ] ]
  DoesNotHaveSiteIpWhitelist: !Equals [ !Ref SiteWhitelistIps, "" ]

Outputs:
  StorageBucketName:
    Description: "The S3 bucket for media uploads"
    Value: !Ref Storage     
    Export:
      Name: !Join [ "", [ !Ref "AWS::StackName", "-StorageBucketName" ] ]  
  SNSTopic:
    Description: "The SNS queue attached to the media uploads bucket; used by yas3fs to notify of changes in the bucket"  
    Value: !Ref StorageTopic
    Export:
      Name: !Join [ "", [ !Ref "AWS::StackName", "-SNSTopic" ] ]
  StorageUser:
    Description: A user allowed to access the shared bucket for the use of MOJIntranet containers
    Value: !Ref StorageUser
    Export:
      Name: !Join [ "", [ !Ref "AWS::StackName", "-StorageUser" ] ]    

Resources:    
  ##
  # Uploads storage
  ##
  Storage:
    Type: AWS::S3::Bucket
    DeletionPolicy : "Retain"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "Delete old backup versions after 30 days"
            NoncurrentVersionExpirationInDays: 30
            Status: Enabled
  StorageBucketPolicyWhitelisted:
    Type: AWS::S3::BucketPolicy
    Condition: HasSiteIpWhitelist
    Properties:
      Bucket: !Ref Storage
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref Storage, '/uploads/*' ] ]
            Principal: "*"
            Condition:
              IpAddress:
                aws:SourceIp: !Split [ "," , !Ref SiteWhitelistIps ]
  StorageBucketPolicyPublic:
    Type: AWS::S3::BucketPolicy
    Condition: DoesNotHaveSiteIpWhitelist
    Properties:
      Bucket: !Ref Storage
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref Storage, '/uploads/*' ] ]
            Principal: "*"
  StorageTopic:
    Type: AWS::SNS::Topic
  StorageUser:
    Type: AWS::IAM::User
    Properties:
      Groups: !FindInMap [ EnvironmentMap, !Ref Environment, StorageUserGroups ]
      Policies:
        - PolicyName: yas3fs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:AbortMultipartUpload
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListMultipartUploadParts
                  - s3:PutObject
                  - s3:RestoreObject
                  - s3:ListBucket
                Effect: Allow
                Resource:
                  - !Join [ '', [ 'arn:aws:s3:::', !Ref Storage ] ]
                  - !Join [ '', [ 'arn:aws:s3:::', !Ref Storage, '/*' ] ]
              - Action:
                  - sns:ConfirmSubscription
                  - sns:GetTopicAttributes
                  - sns:Publish
                  - sns:Subscribe
                  - sns:Unsubscribe
                Effect: Allow
                Resource: !Ref StorageTopic
              - Action: sqs:*
                Effect: Allow
                Resource: !Join [ '', [ 'arn:aws:sqs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':yas3fs-*' ] ]

